### ISSUE TITLE
Strange interaction with can can.

### ISSUE THREAD

**Issue by michaltn** [tchandy/octopus#205]
when I call authorize! from can can gem Octopus seems to lose its shard selection.

The following code works:

``` ruby
around_filter :select_shard

  def select_shard(&block)
    Octopus.using(:avail_reports_shard, &block)
  end

  def index
    @avail_report = Admin::AvailReport.find(params[:avail_report_id])
    proposed_locations = Admin::ProposedLocation.where(:avail_report_id =>  @avail_report.id).order(:id)
    respond_to do |format|
      format.csv do
        send_data proposed_locations.as_csv, :filename => "#{@avail_report.name}.csv", :disposition => 'attachment'
      end
    end
  end
```

The following fails with relation "proposed_locations" does not exist (the query is attempted on the :master shard and the table exists only on :avail_reports_shard):

``` ruby
  around_filter :select_shard

  def select_shard(&block)
    Octopus.using(:avail_reports_shard, &block)
  end

  def index
    @avail_report = Admin::AvailReport.find(params[:avail_report_id])
    authorize! :manage, @avail_report
    proposed_locations = Admin::ProposedLocation.where(:avail_report_id =>  @avail_report.id).order(:id)
    respond_to do |format|
      format.csv do
        send_data proposed_locations.as_csv, :filename => "#{@avail_report.name}.csv", :disposition => 'attachment'
      end
    end
  end
```

**Comment by sobrinho** [comment]
I need more information about this to track down the issue, feel free to reopen if this is still happening on latest release.

**Comment by AdamQuadmon** [comment]
I think the problem lies in the [CanCanCan controller_resource](https://github.com/CanCanCommunity/cancancan/blob/v1.13.1/lib/cancan/controller_resource.rb#L111)
the problem rise when the find method is called on the model to load the resource, loading a collection have no issues.

My configuration is like this:
```ruby
# controller
class Api::Cms::RoutesController < Api::BaseController
  load_and_authorize_resource :class => ::Cms::Route

#ability
can :manage, [::Cms::Route]
```

This way the Route collection is loaded and authenticated but the update method fails.

In order to make the PUT work I need to call the using method like this

```ruby
class Api::Cms::RoutesController < Api::BaseController
  load_and_authorize_resource :class => ::Cms::Route.using(:cms_db)
```

but then we lose the ability to load the collection.

Maybe if I'll be able to point each action to the right syntax or to override the find method on the model to let cancancan use the shards itself it's possible to work around this.

Or maybe there is a simpler solution I'm not thinking.
There are no issues on the CanCanCan side referencing octopus, the only reference I found is here, that's why I'm not asking to the CanCanCan side.

I'll go on my search, let me know if you have any suggestions.
