### ISSUE TITLE
Dynamic shards connection

### ISSUE THREAD

**Issue by macpoint** [tchandy/octopus#226]
Hi all,

I am using the dynamic shards configuration as described in the wiki but I have a problem since updating to 0.8.1. Prior to this I was running 0.5.0beta and everything was ok. 

The thing is that I need to initialise shards for databases that do not exists yet when starting the app. My databases have auto incremented names (like DB_00001, DB_00002, etc) and are created by users in my app. Of course, when created, connection to the DB should be established and thus a shard must exist. Therefore I need to initialise the shard prior to creating the DB. 

In 0.5.0beta it was ok - the app stared with dynamic shards, say, DB_00001 .. DB_00020 but only DBs 1 - 10 existed when starting the app. The rest (11 - 20) were created using the app itself and everyone was happy. 

With 0.8.1 I get (when accessing root_url):

```
Mysql2::Error (Unknown database 'db_00011'):
  mysql2 (0.3.11) lib/mysql2/client.rb:44:in `connect'
  mysql2 (0.3.11) lib/mysql2/client.rb:44:in `initialize'
```
If I understand it correctly, octopus tries to connect to all shards defined in the configuration. It there a way to override this behaviour?

EDIT:
Or better - is there any way to dynamically add shards without modifying the shards.yml / octopus initializer file(s)? 

Thank you.

**Comment by sobrinho** [comment]
I wouldn't recommend you to add shards on memory since it may lead to a lot of bugs.

What would happen if you have many processes? Only the one which received the request would know about that new shard.

And currently your database must exists to be on shards.yml, otherwise octopus will fail to connect.

Although #323 may help you with that since we are going to support failed slaves.
