### ISSUE TITLE
Lazily creating connection pools

### ISSUE THREAD

**Issue by ghempton** [tchandy/octopus#238]
I am exploring creating a separate database for every user (or group of users) in our application and octopus seems like a strong contender for this.

After spending some time looking over the code, it looks like a connection pool is created for *all* shards at initialization time in `proxy.rb` . Naturally this problematic for my use case for two reason:

1. I need to connect to databases that potentially do not exist when the application is started– e.g. a new user is created.
2. Once the application has a relatively large number of users, it seems prohibitively expensive to create a connection pool for *every* user's database during initialization. Ideally a connection pool would be created the first time that a particular shard needs to be accessed.

On the bright side, it seems as though it wouldn't be too much work to access the shards inside of `proxy.rb` lazily and to also add a way to dynamically add shard configurations at run time.

Thoughts? Am I crazy to attempt a database-per-tenant application in Rails?

This seems related to #226.

**Comment by sobrinho** [comment]
Like I've said on #226 I wouldn't recommend you to add shards dynamically to a running application since it may lead to a lot of issues.

Although if you are looking to a way to handle failed slaves, you could follow #323.

A lazy connection pool also may help you with that but the concerns would still remains.
