### ISSUE TITLE
Is there a way to load data from master (globally) if slave didn't received it yet?

### ISSUE THREAD

**Issue by nyku** [tchandy/octopus#250]
in case of replication lag
kind of configuration like

```yaml
try_to_read_from_master_if_slave_didnt_found_the_record_yet: true
```

**Comment by prcongithub** [comment]
We are facing this exact issue. Any solution to this finally?

**Comment by n3bulous** [comment]
If you don't need sharding, I just saw this the other day: https://github.com/eagletmt/switch_point

**Comment by sobrinho** [comment]
There is no easy way to fix that since it always depends on your use case and there is no good default for octopus at all.

`ActiveRecord::RecordNotFound` not necessary means the data didn't replicated yet, the record may not exists at all and it opens a door where someone could attack your application using DoS on your master database.


You could see #68 where I propose a threshold time but it won't fit for all cases.

There is no good default because there is a lot of octopus users using followers to deal with background jobs (i.e.: send emails) that depending may suffer from the delay or not.

If you are using sidekiq you can just let it retry until the data becomes available on follower or simply schedule the job to be processed in a couple minutes instead of right now.

At the application itself, you must analyse your requirements to decide a good solution.


Sorry for that, we are trying to decide a good default but there is higher priorities on the project right now.
