### ISSUE TITLE
Octopus.using does not work

### ISSUE THREAD

**Issue by akicho8** [tchandy/octopus#301]
Even enclosed in Octopus.using("green"), it does not switch to green shard.

Excerpt from https://github.com/akicho8/octopus_has_many_relation/blob/master/test/models/user_test.rb
```ruby
class UserTest < ActiveSupport::TestCase
  test "Octopus.using" do
    user = User.using(:master).create!
    Article.using("green").create!(:user => user)
    Octopus.using("green") do
      assert_equal 1, user.articles.count      # <-- result is 0. why?
    end
  end
end
```

Small app to reproduce
https://github.com/akicho8/octopus_has_many_relation

I have been troubled. Please tell me if there is whether solutions.

**Comment by t1732** [comment]
I have same problem too.
I want to know how to resolve too.

**Comment by akicho8** [comment]
:disappointed_relieved:

**Comment by tchandy** [comment]
Hi Folks,

I'll try to take a look at this issue today.

Thiago

**Comment by akicho8** [comment]
Thanks:joy:

**Comment by tchandy** [comment]
Hi @akicho8 / @t1732 ,

The main problem with your app is that you are mixing data between shards. First, you create an user object on master, and them create an article on green shard. 

Octopus is designed (and only supports code that way) to make sure that every object knows the shard that it belongs. Since the user object belongs to master shard,  when you do user.article.count, it will send the query to the master shard. The correct way to count articles on green shard would be: 

```` ruby
    Octopus.using(:green) do
      assert_equal 1, Article.count
    end
```` 
I'm going to close this issue. If you have other additional problems, please fell free to reopen.

Thiago

**Comment by akicho8** [comment]
@tchandy Thank your reply.
